version: '2.1'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
